apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  selector:
    matchLabels:
      app: api
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: cyrilbkr/testapp
        resources:
          requests:
            memory: "64Mi"
            cpu: "0.1"
          limits:
            memory: "2048Mi"
            cpu: "1.5"
        livenessProbe:
          tcpSocket:
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
        ports:
        - containerPort: 3000

