apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: testapi
  annotations:
    app.kubernetes.io/name: loadtester
    app.kubernetes.io/instance: flagger
  labels:
    app: api
spec:
  ports:
  - port: 3000
    protocol: TCP
  selector:
    app: api
